#!/bin/zsh

antibody bundle < "$HOME/.antibody/.zsh_plugins.txt" > "$HOME/.antibody/.zsh_plugins.sh"
echo "Finished antibody bundle.\n"

echo "Bundle for static loading: \n"
cat "$HOME/.antibody/.zsh_plugins.sh"

echo "\nFIN."

