[kubernetes]
disabled = true
format = '[⛵ $context \($namespace\)](dimmed green) '

[gcloud]
disabled = true

[git_status]
disabled = false

[battery]
disabled = true

[aws]
disabled = true

[k8s]
disabled = true